### ISSUE TITLE
Value is immediately overwritten

### ISSUE THREAD

**Issue by module17** [KepplerPl/url#16]
https://github.com/KepplerPl/url/blob/c176d5c146f1d67fbebda550cdd8ddbffa4d52fc/src/Parser/Parser.php#L100

The explode() should likely be within an else condition.

**Comment by KepplerPl** [comment]
Could you provide an example of the behaviour you had in mind?

**Comment by module17** [comment]
Please close issue. Resolved with #19 merge.
