### ISSUE TITLE
Why not parse_str? 

### ISSUE THREAD

**Issue by adrianmiu** [KepplerPl/url#17]
https://github.com/KepplerPl/url/blob/4ffe53808af40079b50e8a42cab9b337a61a886e/src/Parser/Bags/QueryBag.php#L28

https://secure.php.net/manual/en/function.parse-str.php

**Comment by adrianmiu** [comment]
That function is not deprecated in 7.2, only a specific usage ... "without the result parameter"

Using this function without the result parameter is highly DISCOURAGED and DEPRECATED as of PHP 7.2.

**Comment by adrianmiu** [comment]
Plus, your method doesn't correctly parse string like `"first=value&arr[]=foo+bar&arr[]=baz"`

**Comment by KepplerPl** [comment]
My mistake. Good point tho. I'll get that fixed.
